[package]
name = "class-to-json"
version = "1.0.0"
authors = ["Dmitry Zlykh <Dmitry_Zlykh>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
uuid =  { version = "0.8.2", features = ["v4"] }
clipboard-win = "4.0.3"
dirs = "3.0.1"
chrono = "0.4"

[[bin]]
name = "c2j"
path = "src/main.rs"
